### PR TITLE
Tct itinerary concert

### PR DESCRIPTION
**Pull request by TrinityChristiana**
git fetch --all 
git checkout tct-itinerary-concert

Check that save button adds concerts to itinerary

### CODE REVIEW

**Comment by Iandonmorgan** [comment]
It looks like something may be broken in the search by genre. Hard to believe there aren't any country events coming up in Nashville... 😄

**Review by Iandonmorgan — CHANGES_REQUESTED** [review]
Wanna find what is broken before we merge this in?

**Comment by TrinityChristiana** [comment]
Fixed the problem

**Review by MattCrook — APPROVED** [review]

**Review by Iandonmorgan — APPROVED** [review]
👍

**Pull request merged**
